# Generated by Django 4.0.5 on 2022-06-23 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'eps', 'pdf'], message='Неправильный формат!')])),
                ('info', models.CharField(max_length=50)),
                ('phone_num', models.CharField(default='(555) 555 555', max_length=20)),
            ],
        ),
    ]
