# Generated by Django 4.0.5 on 2022-06-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_rename_footer_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='Second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messenger', models.CharField(choices=[('W/A', 'WhatsApp'), ('TG', 'Telegram'), ('ML', 'Mail'), ('INS', 'Instagram'), ('PN', 'Phone')], max_length=30)),
                ('url_or_phone', models.URLField(max_length=255)),
            ],
        ),
    ]
