# Generated by Django 4.0.5 on 2022-06-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0003_second'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='First',
            new_name='FirstFooterTab',
        ),
        migrations.RenameModel(
            old_name='Second',
            new_name='SecondFooterTab',
        ),
    ]
