# Generated by Django 4.0.5 on 2022-06-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
