# Generated by Django 4.0.5 on 2022-06-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_aboutus_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
