# Generated by Django 4.0.5 on 2022-06-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
